/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 *
 * NOTE: During the transitional period to cookie-based authentication,
 * the backend accepts both Authorization headers and cookies for auth.
 * Login and refresh endpoints also set HttpOnly cookies in responses.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** Refresh Token cookie set by backend during login/refresh */
                refresh_token?: string;
            };
        };
        get?: never;
        put?: never;
        /** Refresh Token */
        post: operations["refresh_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** Access Token cookie set by backend during login/refresh */
                access_token?: string;
            };
        };
        /** Get Me */
        get: operations["get_me_api_v1_auth_me_get"];
        /** Update Me */
        put: operations["update_me_api_v1_auth_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipping/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rates */
        get: operations["get_rates_api_v1_shipping_rates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipping/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shipments */
        get: operations["list_shipments_api_v1_shipping_shipments_get"];
        put?: never;
        /** Create Shipment */
        post: operations["create_shipment_api_v1_shipping_shipments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipping/track/{tracking_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track Shipment */
        get: operations["track_shipment_api_v1_shipping_track__tracking_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipping/shipments/{shipment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shipment */
        get: operations["get_shipment_api_v1_shipping_shipments__shipment_id__get"];
        /** Update Shipment */
        put: operations["update_shipment_api_v1_shipping_shipments__shipment_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipping/shipments/{shipment_id}/label": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Label */
        get: operations["get_label_api_v1_shipping_shipments__shipment_id__label_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Invoices */
        get: operations["list_invoices_api_v1_invoices__get"];
        put?: never;
        /** Create Invoice */
        post: operations["create_invoice_api_v1_invoices__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Invoice */
        get: operations["get_invoice_api_v1_invoices__invoice_id__get"];
        /** Update Invoice */
        put: operations["update_invoice_api_v1_invoices__invoice_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{invoice_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Invoice */
        post: operations["validate_invoice_api_v1_invoices__invoice_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{invoice_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Invoice */
        post: operations["cancel_invoice_api_v1_invoices__invoice_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{invoice_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Invoice Status */
        get: operations["get_invoice_status_api_v1_invoices__invoice_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suppliers */
        get: operations["list_suppliers_api_v1_suppliers__get"];
        put?: never;
        /** Create Supplier */
        post: operations["create_supplier_api_v1_suppliers__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/{supplier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Supplier */
        get: operations["get_supplier_api_v1_suppliers__supplier_id__get"];
        /** Update Supplier */
        put: operations["update_supplier_api_v1_suppliers__supplier_id__put"];
        post?: never;
        /** Delete Supplier */
        delete: operations["delete_supplier_api_v1_suppliers__supplier_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Customers */
        get: operations["list_customers_api_v1_customers__get"];
        put?: never;
        /** Create Customer */
        post: operations["create_customer_api_v1_customers__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Customer */
        get: operations["get_customer_api_v1_customers__customer_id__get"];
        /** Update Customer */
        put: operations["update_customer_api_v1_customers__customer_id__put"];
        post?: never;
        /** Delete Customer */
        delete: operations["delete_customer_api_v1_customers__customer_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Customers */
        post: operations["import_customers_api_v1_customers_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customs/hs-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Hs Codes */
        get: operations["list_hs_codes_api_v1_customs_hs_codes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customs/hs-codes/{hs_code_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hs Code */
        get: operations["get_hs_code_api_v1_customs_hs_codes__hs_code_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customs/calculate-duties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate Duties */
        post: operations["calculate_duties_api_v1_customs_calculate_duties_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customs/declarations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Declarations */
        get: operations["list_declarations_api_v1_customs_declarations_get"];
        put?: never;
        /** Create Declaration */
        post: operations["create_declaration_api_v1_customs_declarations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customs/declarations/{declaration_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Declaration */
        get: operations["get_declaration_api_v1_customs_declarations__declaration_id__get"];
        /** Update Declaration */
        put: operations["update_declaration_api_v1_customs_declarations__declaration_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customs/declarations/{declaration_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Declaration */
        post: operations["submit_declaration_api_v1_customs_declarations__declaration_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resources */
        get: operations["list_resources_api_v1_resources__get"];
        put?: never;
        /** Create Resource */
        post: operations["create_resource_api_v1_resources__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Resources */
        get: operations["search_resources_api_v1_resources_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resource */
        get: operations["get_resource_api_v1_resources__resource_id__get"];
        /** Update Resource */
        put: operations["update_resource_api_v1_resources__resource_id__put"];
        post?: never;
        /** Delete Resource */
        delete: operations["delete_resource_api_v1_resources__resource_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_documents__get"];
        put?: never;
        /** Create Document */
        post: operations["create_document_api_v1_documents__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_documents__document_id__get"];
        /** Update Document */
        put: operations["update_document_api_v1_documents__document_id__put"];
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_api_v1_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description الصفحة الرئيسية — معلومات التطبيق
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description فحص صحة التطبيق — يُستخدم في Monitoring
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_customers_api_v1_customers_import_post */
        Body_import_customers_api_v1_customers_import_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_upload_document_api_v1_documents_upload_post */
        Body_upload_document_api_v1_documents_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Customer */
        Customer: {
            /** Name */
            name: string;
            /** Name En */
            name_en?: string | null;
            /** Contact Person */
            contact_person?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Address */
            address?: string | null;
            /** City */
            city?: string | null;
            /** Country */
            country: string;
            /** Tax Id */
            tax_id?: string | null;
            /** Import License */
            import_license?: string | null;
            /** Category */
            category?: string | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
            /** Created By */
            created_by?: number | null;
        };
        /** CustomerCreate */
        CustomerCreate: {
            /** Name */
            name: string;
            /** Name En */
            name_en?: string | null;
            /** Contact Person */
            contact_person?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Address */
            address?: string | null;
            /** City */
            city?: string | null;
            /** Country */
            country: string;
            /** Tax Id */
            tax_id?: string | null;
            /** Import License */
            import_license?: string | null;
            /** Category */
            category?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** CustomerUpdate */
        CustomerUpdate: {
            /** Name */
            name?: string | null;
            /** Name En */
            name_en?: string | null;
            /** Contact Person */
            contact_person?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Address */
            address?: string | null;
            /** City */
            city?: string | null;
            /** Country */
            country?: string | null;
            /** Tax Id */
            tax_id?: string | null;
            /** Import License */
            import_license?: string | null;
            /** Category */
            category?: string | null;
            /** Status */
            status?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** CustomsDeclaration */
        CustomsDeclaration: {
            /** Shipment Id */
            shipment_id?: number | null;
            /** Hs Code Id */
            hs_code_id?: number | null;
            /**
             * Origin Country
             * @default EG
             */
            origin_country: string;
            /** Destination Country */
            destination_country: string;
            /** Total Value */
            total_value?: number | null;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /**
             * Documents
             * @default []
             */
            documents: string[] | null;
            /** Id */
            id: number;
            /** Declaration Number */
            declaration_number?: string | null;
            /** Duty Amount */
            duty_amount?: number | null;
            /** Tax Amount */
            tax_amount?: number | null;
            /** Total Duties */
            total_duties?: number | null;
            /** Status */
            status: string;
            /** Submitted At */
            submitted_at?: string | null;
            /** Approved At */
            approved_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
            /** Created By */
            created_by?: number | null;
        };
        /** CustomsDeclarationCreate */
        CustomsDeclarationCreate: {
            /** Shipment Id */
            shipment_id?: number | null;
            /** Hs Code Id */
            hs_code_id?: number | null;
            /**
             * Origin Country
             * @default EG
             */
            origin_country: string;
            /** Destination Country */
            destination_country: string;
            /** Total Value */
            total_value?: number | null;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /**
             * Documents
             * @default []
             */
            documents: string[] | null;
        };
        /** CustomsDeclarationUpdate */
        CustomsDeclarationUpdate: {
            /** Shipment Id */
            shipment_id?: number | null;
            /** Hs Code Id */
            hs_code_id?: number | null;
            /** Origin Country */
            origin_country?: string | null;
            /** Destination Country */
            destination_country?: string | null;
            /** Total Value */
            total_value?: number | null;
            /** Currency */
            currency?: string | null;
            /** Status */
            status?: string | null;
            /** Documents */
            documents?: string[] | null;
        };
        /** DeclarationCreateResponse */
        DeclarationCreateResponse: {
            /** Id */
            id: number;
            /** Declaration Number */
            declaration_number: string;
            /** Message */
            message: string;
        };
        /** Document */
        Document: {
            /** Title */
            title: string;
            /**
             * Document Type
             * @default uploaded
             */
            document_type: string;
            /** Template Type */
            template_type?: string | null;
            /** Entity Type */
            entity_type?: string | null;
            /** Entity Id */
            entity_id?: number | null;
            /** Content */
            content?: string | null;
            /**
             * Metadata
             * @default {}
             */
            metadata: Record<string, never> | null;
            /** Id */
            id: number;
            /** File Name */
            file_name?: string | null;
            /** File Path */
            file_path?: string | null;
            /** File Type */
            file_type?: string | null;
            /** File Size */
            file_size?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
            /** Created By */
            created_by?: number | null;
        };
        /** DocumentCreate */
        DocumentCreate: {
            /** Title */
            title: string;
            /**
             * Document Type
             * @default uploaded
             */
            document_type: string;
            /** Template Type */
            template_type?: string | null;
            /** Entity Type */
            entity_type?: string | null;
            /** Entity Id */
            entity_id?: number | null;
            /** Content */
            content?: string | null;
            /**
             * Metadata
             * @default {}
             */
            metadata: Record<string, never> | null;
        };
        /** DocumentUpdate */
        DocumentUpdate: {
            /** Title */
            title?: string | null;
            /** Document Type */
            document_type?: string | null;
            /** Template Type */
            template_type?: string | null;
            /** Entity Type */
            entity_type?: string | null;
            /** Entity Id */
            entity_id?: number | null;
            /** Content */
            content?: string | null;
            /** Metadata */
            metadata?: Record<string, never> | null;
        };
        /** DocumentUploadResponse */
        DocumentUploadResponse: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Message */
            message: string;
        };
        /** DutyCalculationRequest */
        DutyCalculationRequest: {
            /** Hs Code */
            hs_code: string;
            /** Value */
            value: number;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** Destination Country */
            destination_country: string;
            /** Weight Kg */
            weight_kg?: number | null;
        };
        /** DutyCalculationResponse */
        DutyCalculationResponse: {
            /** Hs Code */
            hs_code: string;
            /** Value */
            value: number;
            /** Currency */
            currency: string;
            /** Duty Rate */
            duty_rate: number;
            /** Duty Amount */
            duty_amount: number;
            /** Tax Rate */
            tax_rate: number;
            /** Tax Amount */
            tax_amount: number;
            /** Total Duties */
            total_duties: number;
        };
        /** HSCode */
        HSCode: {
            /** Code */
            code: string;
            /** Description */
            description: string;
            /** Description Ar */
            description_ar?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Duty Rate
             * @default 0
             */
            duty_rate: number;
            /**
             * Tax Rate
             * @default 14
             */
            tax_rate: number;
            /** Restrictions */
            restrictions?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IdResponse */
        IdResponse: {
            /** Id */
            id: number;
            /** Message */
            message: string;
        };
        /** ImportResponse */
        ImportResponse: {
            /** Message */
            message: string;
            /** Count */
            count: number;
        };
        /** Invoice */
        Invoice: {
            /** Customer Id */
            customer_id?: number | null;
            /** Supplier Id */
            supplier_id?: number | null;
            /** Shipment Id */
            shipment_id?: number | null;
            /** Subtotal */
            subtotal: number;
            /**
             * Tax Rate
             * @default 14
             */
            tax_rate: number;
            /** Tax Amount */
            tax_amount?: number | null;
            /** Total */
            total: number;
            /**
             * Currency
             * @default EGP
             */
            currency: string;
            /**
             * Issue Date
             * Format: date
             */
            issue_date: string;
            /** Due Date */
            due_date?: string | null;
            /** Notes */
            notes?: string | null;
            /** Items */
            items: components["schemas"]["InvoiceItem"][];
            /** Id */
            id: number;
            /** Invoice Number */
            invoice_number: string;
            /** Internal Id */
            internal_id?: string | null;
            /** Eta Uuid */
            eta_uuid?: string | null;
            /** Eta Status */
            eta_status?: string | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
            /** Created By */
            created_by?: number | null;
        };
        /** InvoiceCreate */
        InvoiceCreate: {
            /** Customer Id */
            customer_id?: number | null;
            /** Supplier Id */
            supplier_id?: number | null;
            /** Shipment Id */
            shipment_id?: number | null;
            /** Subtotal */
            subtotal: number;
            /**
             * Tax Rate
             * @default 14
             */
            tax_rate: number;
            /** Tax Amount */
            tax_amount?: number | null;
            /** Total */
            total: number;
            /**
             * Currency
             * @default EGP
             */
            currency: string;
            /**
             * Issue Date
             * Format: date
             */
            issue_date: string;
            /** Due Date */
            due_date?: string | null;
            /** Notes */
            notes?: string | null;
            /** Items */
            items: components["schemas"]["InvoiceItem"][];
        };
        /** InvoiceCreateResponse */
        InvoiceCreateResponse: {
            /** Id */
            id: number;
            /** Invoice Number */
            invoice_number: string;
            /** Message */
            message: string;
        };
        /** InvoiceItem */
        InvoiceItem: {
            /** Description */
            description: string;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: number;
            /** Total */
            total: number;
        };
        /** InvoiceUpdate */
        InvoiceUpdate: {
            /** Customer Id */
            customer_id?: number | null;
            /** Supplier Id */
            supplier_id?: number | null;
            /** Shipment Id */
            shipment_id?: number | null;
            /** Subtotal */
            subtotal?: number | null;
            /** Tax Rate */
            tax_rate?: number | null;
            /** Tax Amount */
            tax_amount?: number | null;
            /** Total */
            total?: number | null;
            /** Currency */
            currency?: string | null;
            /** Issue Date */
            issue_date?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Status */
            status?: string | null;
            /** Notes */
            notes?: string | null;
            /** Items */
            items?: components["schemas"]["InvoiceItem"][] | null;
        };
        /** LabelResponse */
        LabelResponse: {
            /** Shipment Id */
            shipment_id: number;
            /** Label Url */
            label_url: string;
            /** Message */
            message: string;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** RegisterResponse */
        RegisterResponse: {
            /** Message */
            message: string;
            /** User Id */
            user_id: number;
        };
        /** Resource */
        Resource: {
            /** Title */
            title: string;
            /** Title Ar */
            title_ar?: string | null;
            /** Description */
            description?: string | null;
            /** Description Ar */
            description_ar?: string | null;
            /** Resource Type */
            resource_type: string;
            /** Category */
            category?: string | null;
            /** Url */
            url?: string | null;
            /** Country */
            country?: string | null;
            /**
             * Metadata
             * @default {}
             */
            metadata: Record<string, never> | null;
            /** Id */
            id: number;
            /** File Path */
            file_path?: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
            /** Created By */
            created_by?: number | null;
        };
        /** ResourceCreate */
        ResourceCreate: {
            /** Title */
            title: string;
            /** Title Ar */
            title_ar?: string | null;
            /** Description */
            description?: string | null;
            /** Description Ar */
            description_ar?: string | null;
            /** Resource Type */
            resource_type: string;
            /** Category */
            category?: string | null;
            /** Url */
            url?: string | null;
            /** Country */
            country?: string | null;
            /**
             * Metadata
             * @default {}
             */
            metadata: Record<string, never> | null;
        };
        /** ResourceUpdate */
        ResourceUpdate: {
            /** Title */
            title?: string | null;
            /** Title Ar */
            title_ar?: string | null;
            /** Description */
            description?: string | null;
            /** Description Ar */
            description_ar?: string | null;
            /** Resource Type */
            resource_type?: string | null;
            /** Category */
            category?: string | null;
            /** Url */
            url?: string | null;
            /** Country */
            country?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Metadata */
            metadata?: Record<string, never> | null;
        };
        /** Shipment */
        Shipment: {
            /** Reference */
            reference?: string | null;
            /** Supplier Id */
            supplier_id?: number | null;
            /** Customer Id */
            customer_id?: number | null;
            /** Origin */
            origin: string;
            /** Destination */
            destination: string;
            /** Carrier */
            carrier?: string | null;
            /** Service Type */
            service_type?: string | null;
            /** Weight */
            weight?: number | null;
            /**
             * Weight Unit
             * @default kg
             */
            weight_unit: string;
            /** Dimensions */
            dimensions?: string | null;
            /** Value */
            value?: number | null;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /**
             * Items Count
             * @default 1
             */
            items_count: number;
            /** Description */
            description?: string | null;
            /** Eta */
            eta?: string | null;
            /** Id */
            id: number;
            /** Tracking Number */
            tracking_number?: string | null;
            /** Status */
            status: string;
            /** Customs Declaration Id */
            customs_declaration_id?: number | null;
            /** Shipped At */
            shipped_at?: string | null;
            /** Delivered At */
            delivered_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
            /** Created By */
            created_by?: number | null;
        };
        /** ShipmentCreate */
        ShipmentCreate: {
            /** Reference */
            reference?: string | null;
            /** Supplier Id */
            supplier_id?: number | null;
            /** Customer Id */
            customer_id?: number | null;
            /** Origin */
            origin: string;
            /** Destination */
            destination: string;
            /** Carrier */
            carrier?: string | null;
            /** Service Type */
            service_type?: string | null;
            /** Weight */
            weight?: number | null;
            /**
             * Weight Unit
             * @default kg
             */
            weight_unit: string;
            /** Dimensions */
            dimensions?: string | null;
            /** Value */
            value?: number | null;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /**
             * Items Count
             * @default 1
             */
            items_count: number;
            /** Description */
            description?: string | null;
            /** Eta */
            eta?: string | null;
        };
        /** ShipmentCreateResponse */
        ShipmentCreateResponse: {
            /** Id */
            id: number;
            /** Tracking Number */
            tracking_number: string;
            /** Message */
            message: string;
        };
        /** ShipmentTrackingResponse */
        ShipmentTrackingResponse: {
            /** Id */
            id: number;
            /** Tracking Number */
            tracking_number?: string | null;
            /** Status */
            status: string;
            /** Tracking Events */
            tracking_events: Record<string, never>[];
        };
        /** ShipmentUpdate */
        ShipmentUpdate: {
            /** Reference */
            reference?: string | null;
            /** Supplier Id */
            supplier_id?: number | null;
            /** Customer Id */
            customer_id?: number | null;
            /** Origin */
            origin?: string | null;
            /** Destination */
            destination?: string | null;
            /** Carrier */
            carrier?: string | null;
            /** Service Type */
            service_type?: string | null;
            /** Weight */
            weight?: number | null;
            /** Weight Unit */
            weight_unit?: string | null;
            /** Dimensions */
            dimensions?: string | null;
            /** Value */
            value?: number | null;
            /** Currency */
            currency?: string | null;
            /** Items Count */
            items_count?: number | null;
            /** Description */
            description?: string | null;
            /** Status */
            status?: string | null;
            /** Eta */
            eta?: string | null;
            /** Shipped At */
            shipped_at?: string | null;
            /** Delivered At */
            delivered_at?: string | null;
        };
        /** ShippingRate */
        ShippingRate: {
            /** Carrier */
            carrier: string;
            /** Service */
            service: string;
            /** Estimated Days */
            estimated_days: number;
            /** Cost */
            cost: number;
            /** Currency */
            currency: string;
        };
        /** ShippingRateRequest */
        ShippingRateRequest: {
            /** Origin */
            origin: string;
            /** Destination */
            destination: string;
            /** Weight */
            weight: number;
            /**
             * Weight Unit
             * @default kg
             */
            weight_unit: string;
            /** Dimensions */
            dimensions?: string | null;
            /** Value */
            value?: number | null;
        };
        /** Supplier */
        Supplier: {
            /** Name */
            name: string;
            /** Name En */
            name_en?: string | null;
            /** Contact Person */
            contact_person?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Address */
            address?: string | null;
            /** City */
            city?: string | null;
            /**
             * Country
             * @default Egypt
             */
            country: string;
            /** Tax Id */
            tax_id?: string | null;
            /** Commercial Registry */
            commercial_registry?: string | null;
            /**
             * Certificates
             * @default []
             */
            certificates: string[] | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
            /** Created By */
            created_by?: number | null;
        };
        /** SupplierCreate */
        SupplierCreate: {
            /** Name */
            name: string;
            /** Name En */
            name_en?: string | null;
            /** Contact Person */
            contact_person?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Address */
            address?: string | null;
            /** City */
            city?: string | null;
            /**
             * Country
             * @default Egypt
             */
            country: string;
            /** Tax Id */
            tax_id?: string | null;
            /** Commercial Registry */
            commercial_registry?: string | null;
            /**
             * Certificates
             * @default []
             */
            certificates: string[] | null;
            /** Notes */
            notes?: string | null;
        };
        /** SupplierUpdate */
        SupplierUpdate: {
            /** Name */
            name?: string | null;
            /** Name En */
            name_en?: string | null;
            /** Contact Person */
            contact_person?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Address */
            address?: string | null;
            /** City */
            city?: string | null;
            /** Country */
            country?: string | null;
            /** Tax Id */
            tax_id?: string | null;
            /** Commercial Registry */
            commercial_registry?: string | null;
            /** Certificates */
            certificates?: string[] | null;
            /** Status */
            status?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** User */
        User: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone?: string | null;
            /** Company */
            company?: string | null;
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone?: string | null;
            /** Company */
            company?: string | null;
            /** Password */
            password: string;
            /**
             * Role
             * @default Customer
             */
            role: string;
        };
        /** UserLogin */
        UserLogin: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Company */
            company?: string | null;
            /** Role */
            role?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationResponse */
        ValidationResponse: {
            /** Message */
            message: string;
            /** Status */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** Refresh Token cookie set by backend during login/refresh */
                refresh_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** Access Token cookie set by backend during login/refresh */
                access_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    update_me_api_v1_auth_me_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** Access Token cookie set by backend during login/refresh */
                access_token?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rates_api_v1_shipping_rates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShippingRateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShippingRate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shipments_api_v1_shipping_shipments_get: {
        parameters: {
            query?: {
                status?: string | null;
                customer_id?: number | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_shipment_api_v1_shipping_shipments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShipmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_shipment_api_v1_shipping_track__tracking_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tracking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentTrackingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shipment_api_v1_shipping_shipments__shipment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_shipment_api_v1_shipping_shipments__shipment_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShipmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_label_api_v1_shipping_shipments__shipment_id__label_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invoices_api_v1_invoices__get: {
        parameters: {
            query?: {
                status?: string | null;
                customer_id?: number | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invoice_api_v1_invoices__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_invoice_api_v1_invoices__invoice_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_invoice_api_v1_invoices__invoice_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_invoice_api_v1_invoices__invoice_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_invoice_api_v1_invoices__invoice_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_invoice_status_api_v1_invoices__invoice_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_suppliers_api_v1_suppliers__get: {
        parameters: {
            query?: {
                search?: string | null;
                status?: string | null;
                city?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supplier"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_supplier_api_v1_suppliers__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_supplier_api_v1_suppliers__supplier_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supplier"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_supplier_api_v1_suppliers__supplier_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_supplier_api_v1_suppliers__supplier_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_customers_api_v1_customers__get: {
        parameters: {
            query?: {
                search?: string | null;
                status?: string | null;
                country?: string | null;
                category?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_customer_api_v1_customers__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_api_v1_customers__customer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_customer_api_v1_customers__customer_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_customer_api_v1_customers__customer_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_customers_api_v1_customers_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_customers_api_v1_customers_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hs_codes_api_v1_customs_hs_codes_get: {
        parameters: {
            query?: {
                search?: string | null;
                category?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HSCode"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hs_code_api_v1_customs_hs_codes__hs_code_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hs_code_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HSCode"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_duties_api_v1_customs_calculate_duties_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DutyCalculationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DutyCalculationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_declarations_api_v1_customs_declarations_get: {
        parameters: {
            query?: {
                status?: string | null;
                shipment_id?: number | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomsDeclaration"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_declaration_api_v1_customs_declarations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomsDeclarationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeclarationCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_declaration_api_v1_customs_declarations__declaration_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                declaration_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomsDeclaration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_declaration_api_v1_customs_declarations__declaration_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                declaration_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomsDeclarationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_declaration_api_v1_customs_declarations__declaration_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                declaration_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resources_api_v1_resources__get: {
        parameters: {
            query?: {
                resource_type?: string | null;
                category?: string | null;
                country?: string | null;
                search?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_resource_api_v1_resources__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_resources_api_v1_resources_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resource_api_v1_resources__resource_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_resource_api_v1_resources__resource_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_resource_api_v1_resources__resource_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_documents__get: {
        parameters: {
            query?: {
                document_type?: string | null;
                entity_type?: string | null;
                entity_id?: number | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_api_v1_documents__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_document_api_v1_documents__document_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_documents_upload_post: {
        parameters: {
            query?: {
                title?: string | null;
                entity_type?: string | null;
                entity_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
