"""initial

Revision ID: 9f6e6d58ca0f
Revises: 
Create Date: 2026-07-04 15:45:35.392526
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9f6e6d58ca0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
